[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
viaIR = true

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    # '@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts',
    # '@uniswap/v3-core/contracts=lib/v3-core/contracts',
    '@aave/v3-core/contracts=lib/aave-v3-core/contracts',
    '@aave/v3-periphery/contracts=lib/aave-v3-periphery/contracts',
    # '@comet/contracts=lib/comet/contracts',
]

[rpc_endpoints]
# Use ${VARIABLE_NAME} syntax to reference environment variables
polygon = "${POLYGON_RPC_URL}"
ethereum = "${ETH_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
optimism = "${OP_RPC_URL}"

[etherscan]
# API Keys for contract verification
polygon = { key = "${ETHERSCAN_API_KEY}" }
ethereum = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${ETHERSCAN_API_KEY}" }
